name: Extend CI

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git setting
        run: |
            git pull
            git config --global user.name ${{ secrets.YOUSER_NAME }}
            git config --global user.email ${{ secrets.MAIL_ADDRESS }}
            
      - name: Commit and push
        run: |
          git commit --allow-empty -m "chore: prevent automatic workflow stopping" -m "see: https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow"
          git push
